import React from 'react'
import { Link } from 'react-router-dom'

/* Generated by ChatGTP 4.0 to get the date and time to be the correct format */
const formatDateToReadable = (dateString) => {
  const date = new Date(dateString);
  const formattedDate = new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  }).format(date);

  const formattedTime = date.toLocaleTimeString('en-US', {
    hour: 'numeric',
    hour12: true,
  });

  return `${formattedDate} - ${formattedTime}`;
};

const EventItem = ({item}) => {
  return (
    <Link to={`/events/${item.id}`}>
        <div className='event-card'>
            <div className='event-image'>{item.image}</div>
            <div className='event-info'>
               <div className='event-date'>{formatDateToReadable(item.eventDate)}</div>
              <div className='event-title'>{item.title}</div>
              <div className='event-location'><i className="fa-solid fa-location-dot"></i>{item.location}</div>
            </div>
        </div>
    </Link>
  )
}

export default EventItem