import React from 'react'
import { useLocation } from 'react-router-dom';

/* Generated by ChatGPT 4.0 to get the title for every page to be able to change it depending on the URL */
const Header = () => {
  const location = useLocation();

  const getTitle = () => {
    switch (location.pathname) {
      case '/':
        return 'Events';
      case '/booking':
        return 'booking';
      case '/events/':
        return 'Events';
      default:
        return 'Ventixe';
    }
  };
  return (
    <header><h1>{getTitle()}</h1></header>
  )
}

export default Header