import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';


// Code generated by ChatGPT 4.o to get the header title to change depending on wich page you're on, and added a arrow to get back to previous page
const Header = () => {
  const location = useLocation();
  const navigate = useNavigate();

  const showBackArrow = location.pathname.startsWith('/events') || location.pathname.startsWith('/booking');

  const getTitle = () => {
    if (location.pathname === '/') return 'Events';
    if (location.pathname.startsWith('/events')) return 'Event Details';
    if (location.pathname.startsWith('/booking')) return 'Book Event';
    return 'Ventixe';
  };

  return (
    <header>
        {showBackArrow && (
        <a onClick={() => navigate(-1)} style={{ fontSize: '1.5rem', cursor: 'pointer' }}>
         <i className="fa-solid fa-arrow-left"></i>
        </a>
      )}
      <h1>{getTitle()}</h1>
    </header>
  );
};

export default Header;
