import React from 'react'
import { NavLink, useLocation, useNavigate } from 'react-router-dom'

// Code generated with help from ChatGPT 4.o to get the navbar on mobile to change title depending on wich page you're on, and added a arrow to get back to previous page. 
const Navlinks = () => {
  const location = useLocation();
  const navigate = useNavigate();

  const showBackArrow = location.pathname.startsWith('/events') || location.pathname.startsWith('/booking')
   const getTitle = () => {
    if (location.pathname === '/') return 'Events'
    if (location.pathname.startsWith('/events')) return 'Event Details'
    if (location.pathname.startsWith('/booking')) return 'Book Event'
    return 'Ventixe'
  }

  return (
    <div className="navlinks">
      {/* navlink-mobile-header generated by ChatGPT 4.0 */}
        <div className="navlink-mobile-header">
        {showBackArrow && (
          <span onClick={() => navigate(-1)} style={{ fontSize: '1.2rem', cursor: 'pointer' }}>
            <i className="fa-solid fa-chevron-left"></i>
          </span>
        )}
        <span className="mobile-title">{getTitle()}</span>
      </div>

        <NavLink className="navlink" to={`/`}><i className="fa-solid fa-ticket"></i> Events </NavLink>
        <NavLink className="navlink-tablet" to={`/`}><i className="fa-solid fa-ticket"></i></NavLink>

    </div>
  )
}

export default Navlinks